

{ +block{test} }
.static.affiliate.rakuten.co.jp
.afl.rakuten.co.jp
.truoptik.com
.disquscdn.com
www.youtube.com/embed/wZLMIXWGhwQ
livedoor.blogimg.jp/himasoku123/imgs/c/d
www.freem.ne.jp/win/game/7490
moba8.net
www.facebook.com/plugins/like.php
platform.twitter.com
rranking12.ziyu.net
spdeliverp.i-mobile.co.jp
www.google-analytics.com
ssl.google-analytics.com
cdn.ad.maist.jp
graph.facebook.com
rt.gsspat.jp
twitter.com/intent/
www.facebook.com/share\.php
shinobi.jp
i-mobile.co.jp
prwidgets.com
.adk2x.com
cinablitz.com
.zoomtv.me

{ +block{tumblr} }
tag.researchnow.com
.geo.yahoo.com
geo.query.yahoo.com
.cedexis-test.com
bam.nr-data.net
.cedexis.com

{ +block{mobile} }
googleads.g.doubleclick.net

{ -block -filter -fast-redirects -hide-referrer }
iourpg.com

{ +block{Facebook like and similar tracking URLs} +handle-as-image }
www.facebook.com/(extern|plugins)/(login_status|like(box)?|activity|fan)\.php
platform.twitter.com/widgets/follow_button?
plusone.google.com
