#!/bin/sh

umask 027
if [ -x /usr/local/sbin/delegated ]; then
        echo -n ' delegated'
	/usr/local/sbin/delegated -P8080  \
        SERVER=http \
        CHARCODE=UTF8 \
        CACHE=do \
        CRON="0 2 * * * -expire 2d" \
        EXPIRE=2d \
#        CACHEDIR=/var/spool/delegate/cache \
        > /dev/null 2>&1
fi
